### ISSUE TITLE
主线 2K 支持 Roadmap

### ISSUE THREAD

**Issue by xen0n** [loongson-community/linux-wip#1]
整理自 flygoat 聊天记录里说的话

### Full DT boot

* [ ] CPU Node
* [ ] 允许 LIOINTC 多实例指向相应的 CPU
* [ ] IPI 梳理

### 我理解的杂项工作

* [ ] ISA bus 注册进 Logic PIO
* [ ] 用户态 MSAIR/MSACSR 访问辅助
